### ISSUE TITLE
Story: Make KokkosKernels build independently of Trilinos

### ISSUE THREAD

**Issue by crtrott** [kokkos/kokkos-kernels#1]
- [x] Fix TpetraKernels names to KokkosKernels #4 
- [x] Stop using Teuchos in tests #2  
- [x] Move Tpetra::Details::OrdinalTraits to KokkosKernels #22 
- [x] Fix ETI instantiation to be based on Kokkos CMake variables only #5, #20
- [x] Add new ETI system compatible with Makefile-based build system #21
