### ISSUE TITLE
Add KokkosGraph stream support

### ISSUE THREAD

**Issue by e10harvey** [kokkos/kokkos-kernels#1879]
- [ ] graph_mis2_aggregate (required for #1860)
- [ ] graph_explicit_coarsen_with_inverse_map (required for #1860)
- [ ] graph_color_symbolic (required for #1860)
- [ ] ...
