### ISSUE TITLE
Work tracking issue for batched sorting algorithms (#461)

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#473]
This issue is just for discussing work on the radix and bitonic sorting algorithms in PR #461.

Things to do before merging:

- [ ] Documentation in the wiki (when to use each algorithm)
- [ ] Performance results on the benchmark section of wiki
- [ ] Create permanent performance tests in perf_test/
- [x] Use KokkosBatched naming conventions (capitalized "Vector" or "Team" before the name)
- [x] Make sure league/team sizes are correct for the global bitonic sort. Right now, league size is hardcoded to 256 and team size is just ceil(n / 256).
- [x] Add a unit test that uses a custom comparator in Bitonic.
