### ISSUE TITLE
Work tracking issue for cluster Gauss-Seidel (#455)

### ISSUE THREAD

**Issue by brian-kelley** [kokkos/kokkos-kernels#475]
An issue for tracking work and discussing the cluster Gauss-Seidel pull request #455.

- [x] Wiki update under "Sparse"
- [ ] Benchmarks for a selection (or all) the SPD matrices from the SuiteSparse collection. Compare setup time, solve time and iteration count.
- [x] Add permanent performance tests that do the above
- [x] Add this as a feature in Ifpack2::Relaxation
- [x] Make sure reasonable default cluster size is chosen, and document it
- [x] (When merged): open new issues for exposing RCM reordering and breadth-first search as first-class features of KokkosGraph.
- [x] (When #461 is merged): delete the radix sort implementation that is currently local to KokkosSparse_rcm_impl. Instead use radix or bitonic, depending on the execution space.

New things (11-1-19):
- [ ] Add CUDA graph support (for CUDA >= 10.1) to reduce kernel launches
- [x] (When merged): add graph clustering/partitioning as a first-class feature of KokkosGraph. Maybe make a higher-quality version that refines the partitioning to minimize #cut edges.

New thing (11-8-19):
- [x] Add support for multiple vector (rank-2) X and Y. See #488 

New thing (12-12-19):
- [ ] Resolve #495 (balanced coloring) for performance

**Comment by srajama1** [comment]
Note Ifpack2 changes can come after the Kokkos 3.0 merge into Trilinos.
