### ISSUE TITLE
Post-CMake merge and 3.0 items

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos-kernels#486]
Reminder list of items following merge of ~~#471 (previous)~~ now #491 

- [x] Re-enable `-Werror` for the clang builds on kokkos-dev-2 when we resume testing off of Kokkos' develop branch
- [x] Add more testing configurations to kokkos-dev-2 (cover items in spot-check)
- [x] Convert testing to use test_all_sandia replacement script patterned from kokkos' cm_test_all_sandia script

**Comment by ndellingwood** [comment]
Some open issues to resolve for 3.0 testing and release:

- [ ] spgemm shmem alignment issues: Issue #500  PR #503 @ndellingwood 

- [ ] spmv unit testing tolerance settings: Issue #506  PR #507 ? @lucbv 

- [ ] dot-based GEMM (Cuda spec) handling of `beta==0` case:  Issue #509  @seheracer 
        Follow-up - possible slight loosening of tolerance in failing Trilinos tests to allow for diffs caused by the parallelism introduced by these performance enhancements

- [ ] spgemm symbolic phase fixes (mem pool, ...)  @brian-kelley 

- [ ] update of Ifpack2 calls to `*gauss_seidel_apply` in `packages/ifpack2/src/Ifpack2_Relaxation_def.hpp` - needs to be added to the 

Adding @srajama1 @crtrott and @jjwilke so they are in the loop.

**Comment by ndellingwood** [comment]
Issues to resolve exposed by Trilinos testing:

- [ ] batched_lu_serial: fix for ambiguous ? operation error (Sacado) : PR #512

**Comment by ndellingwood** [comment]
- [ ] Recent issue in ATDM testing with Tpetra MV following #510 -related patch  
See trilnos/Trilinos#6418

**Comment by ndellingwood** [comment]
- [ ] gemv transpose mode with TPLs #539 
- [ ] perf test link errors #527

**Comment by ndellingwood** [comment]
This was all completed for 3.0, closing.
